// auth & signup
export const LOGIN_REQUEST = 'auth/login-request'
export const LOGIN_SUCCESS = 'auth/login-success'
export const LOGIN_FAILURE = 'auth/login-failure'
export const LOGOUT_DONE = 'auth/logout-done'

// message
export const MESSAGE_APPEND = 'app/message-append'
export const MESSAGE_CLEAR = 'app/message-clear'
export const SHOW_LOADING = 'app/show-loading'
export const CLOSE_LOADING = 'app/close-loading'

// parents
export const GET_PARENTS_REQUEST = 'parents/get-parents-request'
export const GET_PARENTS_SUCCESS = 'parents/get-parents-success'
export const GET_PARENTS_FAILURE = 'parents/get-parents-failure'
export const GET_PARENT_REQUEST = 'parents/get-parent-request'
export const GET_PARENT_SUCCESS = 'parents/get-parent-success'
export const GET_PARENT_FAILURE = 'parents/get-parent-failure'
export const CREATE_PARENT_REQUEST = 'parents/create-parent-request'
export const CREATE_PARENT_SUCCESS = 'parents/create-parent-success'
export const CREATE_PARENT_FAILURE = 'parents/create-parent-failure'
export const UPDATE_PARENT_REQUEST = 'parents/update-parent-request'
export const UPDATE_PARENT_SUCCESS = 'parents/update-parent-success'
export const UPDATE_PARENT_FAILURE = 'parents/update-parent-failure'
export const DELETE_PARENT_REQUEST = 'parents/delete-parent-request'
export const DELETE_PARENT_SUCCESS = 'parents/delete-parent-success'
export const DELETE_PARENT_FAILURE = 'parents/delete-parent-failure'
export const SEARCH_PARENTS_REQUEST = 'parents/search-parents-request'
export const GET_CHILD_REQUEST = 'children/get-child-request'
export const GET_CHILD_SUCCESS = 'children/get-child-success'
export const GET_CHILD_FAILURE = 'children/get-child-failure'
export const CREATE_CHILD_REQUEST = 'children/create-child-request'
export const CREATE_CHILD_SUCCESS = 'children/create-child-success'
export const CREATE_CHILD_FAILURE = 'children/create-child-failure'
export const UPDATE_CHILD_REQUEST = 'children/update-child-request'
export const UPDATE_CHILD_SUCCESS = 'children/update-child-success'
export const UPDATE_CHILD_FAILURE = 'children/update-child-failure'
export const DELETE_CHILD_REQUEST = 'children/delete-child-request'
export const DELETE_CHILD_SUCCESS = 'children/delete-child-success'
export const DELETE_CHILD_FAILURE = 'children/delete-child-failure'
